ORT/Grupo3.ReservaDeCine/Controllers/FuncionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Grupo3.ReservaDeCine.Database;
using Grupo3.ReservaDeCine.Models;
using Microsoft.AspNetCore.Authorization;
using Grupo3.ReservaDeCine.Models.Enums;

namespace Grupo3.ReservaDeCine.Controllers
{
  
    public class FuncionesController : Controller
    {
        private readonly CineDbContext _context;

        public FuncionesController(CineDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Authorize(Roles = nameof(Role.Administrador))]
        public IActionResult Index()
        {
            var funciones = _context
                .Funciones
                .Include(x => x.Pelicula)
                .Include(x => x.Sala)
                .ToList();

            return View(funciones);
        }


        [HttpGet]
        [Authorize(Roles = nameof(Role.Administrador))]
        public IActionResult Details(int? id)
        {
             
            if (id == null)
            {
                return NotFound();
            }

            var funcion = _context.Funciones
                .Include(x => x.Reservas).ThenInclude(x => x.Cliente)
                .Include(x => x.Pelicula)
                .Include(x => x.Sala)
                .FirstOrDefault(m => m.Id == id);

            if (funcion == null)
            {
                return NotFound();
            }

            return View(funcion);
        }


        [HttpGet]
        [Authorize(Roles = nameof(Role.Administrador))]
        public IActionResult Create()
        {
            ViewBag.SelectSalas = new SelectList(_context.Salas, "Id", "Nombre");
            ViewBag.SelectPeliculas = new SelectList(_context.Peliculas, "Id", "Nombre");
            
            return View();
        }


        [HttpPost]
        [Authorize(Roles = nameof(Role.Administrador))]
        [ValidateAntiForgeryToken]
        public  IActionResult Create(Funcion funcion)
        {

            ValidarFecha(funcion);
            ValidarHorario(funcion);
            
            if (ModelState.IsValid)
            {
                var sala = _context.Salas
                             .Where(x => x.Id == funcion.SalaId)
                             .FirstOrDefault();

                funcion.CantButacasDisponibles = sala.CapacidadTotal;

                _context.Add(funcion);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }

            ViewBag.SelectSalas = new SelectList(_context.Salas, "Id", "Nombre");
            ViewBag.SelectPeliculas = new SelectList(_context.Peliculas, "Id", "Nombre");

            return View(funcion);
        }


        [HttpGet]
        [Authorize(Roles = nameof(Role.Administrador))]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcion = _context.Funciones.Find(id);

            if (funcion == null)
            {
                return NotFound();
            }

            ViewBag.SelectSalas = new SelectList(_context.Salas, "Id", "Nombre");
            ViewBag.SelectPeliculas = new SelectList(_context.Peliculas, "Id", "Nombre");

            return View(funcion);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Role.Administrador))]
        public IActionResult Edit(int id, Funcion funcion)
        {

            if (id != funcion.Id)
            {
                return NotFound();
            }
            
            ValidarFecha(funcion);
            ValidarHorario(funcion);
            ValidarCapacidadNuevaSalaSegunReservas(id, funcion);

            if (ModelState.IsValid)
            {
                try
                {
                    // Obtengo la función de la base de datos
                    var funcionDb = _context.Funciones.Find(id);

                    // Mapeo los campos que se pueden editar SalaId, PeliculaId, Fecha, Horario
                    funcionDb.SalaId = funcion.SalaId;
                    funcionDb.PeliculaId = funcion.PeliculaId;
                    funcionDb.Fecha = funcion.Fecha;
                    funcionDb.Horario = funcion.Horario;

                    _context.Update(funcionDb);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {

                    if (!FuncionExists(funcion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewBag.SelectSalas = new SelectList(_context.Salas, "Id", "Nombre");
            ViewBag.SelectPeliculas = new SelectList(_context.Peliculas, "Id", "Nombre");

            return View(funcion);
        }

        [HttpGet]
        [Authorize(Roles = nameof(Role.Administrador))]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcion = _context
                .Funciones
                .Include(x => x.Pelicula)
                .Include(x => x.Sala)
                .FirstOrDefault(x => x.Id == id);
           
            if (funcion == null)
            {
                return NotFound();
            }


            return View(funcion);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Role.Administrador))]
        public IActionResult DeleteConfirmed(int id)
        {
            var funcion = _context.Funciones.Find(id);

            _context.Funciones.Remove(funcion);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        [Authorize(Roles = nameof(Role.Cliente))]
        public IActionResult SeleccionarFiltro()
        {
            ViewBag.SelectPeliculas = new SelectList(_context.Peliculas, "Id", "Nombre");

            return View();
        }


        [AllowAnonymous]
        public IActionResult FiltrarPorPelicula(Pelicula pelicula) //cuando entra por cartelera
        {
            var funciones = _context
                 .Funciones
                 .Include(x => x.Pelicula)
                 .Include(x => x.Sala).ThenInclude(x => x.Tipo)
                 .Where(x => x.PeliculaId == pelicula.Id && x.Fecha >= DateTime.Now)
                 .ToList();

            if (!funciones.Any())
            {
                return RedirectToAction(nameof(NoHayFunciones));
            }

            return View(funciones);
        }

     
        [Authorize(Roles = nameof(Role.Cliente))]
        public IActionResult FiltrarPorPeliculaId(int PeliculaId) // Cuando entra por el filtro día/pelicula
        {
            var funciones =_context
                .Funciones
                .Include(x => x.Pelicula)
                .Include(x => x.Sala).ThenInclude(x => x.Tipo)
                .Where(x => x.Pelicula.Id == PeliculaId && x.Fecha >= DateTime.Now)
                .ToList();

            if (!funciones.Any())
            {
                return RedirectToAction(nameof(NoHayFunciones));
            }

            return View(funciones);
        }


        [Authorize(Roles = nameof(Role.Cliente))]
        public IActionResult FiltrarPorFecha(DateTime Fecha) // Cuando entra por el filtro día/pelicula
        {
            var funciones =
                _context
                .Funciones
                .Include(x => x.Pelicula)
                .Include(x => x.Sala).ThenInclude(x => x.Tipo)
                .Where(x => x.Fecha == Fecha)
                .ToList();

            if(!funciones.Any())
            {
                return RedirectToAction(nameof(NoHayFunciones));
            }

            return View(funciones);
        }


        [HttpGet]
        public IActionResult NoHayFunciones()
        {
            return View();
        }



        ////---- Métodos privados para validaciones ----////

        private bool FuncionExists(int id)
        {
            return _context.Funciones.Any(x => x.Id == id);
        }


        private void ValidarFecha(Funcion funcion)
        {
            if (funcion.Fecha < DateTime.Now) 
            {
                ModelState.AddModelError(nameof(funcion.Fecha), "La fecha no puede ser anterior a la fecha actual");
            }

            if(funcion.Fecha.Year > DateTime.Now.Year + 1)
            {
                ModelState.AddModelError(nameof(funcion.Fecha), "La fecha debe ser dentro del año actual");
            }
        }


        private void ValidarHorario(Funcion funcion)
        {
            if (funcion.Horario.Hour > 1 && funcion.Horario.Hour < 9)
            {
                ModelState.AddModelError(nameof(funcion.Horario), "El horario debe estar comprendido entre las 9:00 y la 01:59 (A.M.)");
            }

            ValidarSalaLibre(funcion);  // Si validar horario esta OK, llama a Validar sala libre

        }

      
        // Valida que la sala se encuentre libre cuando quiero crear o editar una funcion.
        private void ValidarSalaLibre(Funcion f)  
        {
            
            if (_context.Funciones.Any(
                x => x.Fecha == f.Fecha &&
                x.SalaId == f.SalaId &&
               (x.Horario.Hour >= f.Horario.Hour - 3 && x.Horario.Hour <= f.Horario.Hour + 3) &&
                x.Id != f.Id))// verifico que el Id para que la funcion no se encuentre a si misma en caso de edicion
            {
                ModelState.AddModelError(nameof(f.Horario), "La sala está ocupada en ese horario");
            }

ORT/Grupo3.ReservaDeCine/Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Grupo3.ReservaDeCine.Database;
using Grupo3.ReservaDeCine.Models;
using Microsoft.AspNetCore.Authorization;
using Grupo3.ReservaDeCine.Models.Enums;
using System.Security.Claims;
using Microsoft.Extensions.Logging.Console.Internal;
using System.Security.Cryptography.X509Certificates;

namespace Grupo3.ReservaDeCine.Controllers
{
    [Authorize]
    public class ReservasController : Controller
    {
        private readonly CineDbContext _context;

        public ReservasController(CineDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Authorize(Roles = nameof(Role.Administrador))]
        public IActionResult Index()
        {
            var reservas = _context
                 .Reservas
                 .Include(x => x.Cliente)
                 .Include(x => x.Funcion).ThenInclude(x => x.Pelicula)
                 .Include(x => x.Funcion).ThenInclude(x => x.Sala)
                 .ToList();

            return View(reservas);
        }


        [HttpGet]
        [Authorize(Roles = nameof(Role.Administrador))]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserva = _context.Reservas
                 .Include(x => x.Cliente)
                 .Include(x => x.Funcion).ThenInclude(x => x.Pelicula)
                 .FirstOrDefault(x => x.Id == id);

            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }


        [HttpGet]
        [Authorize(Roles = nameof(Role.Cliente))]
        public IActionResult MisReservas()
        {
            int clienteId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value); 

            var reservas = _context
                .Reservas
                .Include(x => x.Funcion).ThenInclude(x => x.Pelicula)
                .Include(x => x.Funcion).ThenInclude(x => x.Sala)
                .Where(reserva => reserva.ClienteId == clienteId && reserva.Funcion.Fecha >= DateTime.Today)
                .ToList();

            return View(reservas);
        }


        [HttpGet]
        [Authorize(Roles = nameof(Role.Cliente))]
        public IActionResult CrearReservaPorFuncion(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcion = _context
                .Funciones
                .Include(x => x.Sala).ThenInclude(x => x.Tipo)
                .FirstOrDefault(x => x.Id == id);

            ViewData["Peliculas"] = new SelectList(_context.Peliculas, "Id", "Nombre", funcion.PeliculaId);
            ViewData["FechaHora"] = new SelectList(_context.Funciones, "Id", "FechaHora", funcion.FechaHora);
            ViewData["CostoEntrada"] = funcion.Sala.Tipo.PrecioEntrada;

            Reserva reserva = new Reserva()
            {
                FuncionId = funcion.Id,
                Funcion = funcion

            };

            return View(reserva);
        }

        [HttpPost]
        [Authorize(Roles = nameof(Role.Cliente))]
        // Aca el server efectiviza la reserva
        public IActionResult CrearReservaPorFuncion([Bind("FuncionId, CantButacas")] Reserva reserva)
        {
            if (!ValidarEdad(reserva))
            {
                ModelState.AddModelError(string.Empty, "No cuenta con edad suficiente para ver esta película");
            }

            var funcion = _context
                .Funciones
                .Include(x => x.Sala).ThenInclude(x => x.Tipo)
                .FirstOrDefault(x => x.Id == reserva.FuncionId);


            if (funcion == null)
                ModelState.AddModelError(nameof(Reserva.Funcion), "La función no se encuentra disponible");

            ValidarCantButacas(reserva, funcion);

            if (ModelState.IsValid)
            {
                reserva.FechaDeAlta = DateTime.Now;
                funcion.CantButacasDisponibles -= reserva.CantButacas;
                reserva.CostoTotal = reserva.CantButacas * funcion.Sala.Tipo.PrecioEntrada;
                reserva.ClienteId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);  // aca le asigna a la reserva el clienteId con el claims de Name Identifier
                _context.Add(reserva);
                _context.SaveChanges();
                return RedirectToAction(nameof(MisReservas));
            }

            ViewData["CostoEntrada"] = funcion.Sala.Tipo.PrecioEntrada;
            ViewData["Peliculas"] = new SelectList(_context.Peliculas, "Id", "Nombre", funcion.PeliculaId);
            ViewData["FechaHora"] = new SelectList(_context.Funciones, "Id", "FechaHora", funcion.FechaHora);

            reserva.Funcion = funcion;

            return View(reserva);
        }


        [HttpGet]
        [Authorize(Roles = nameof(Role.Administrador))]
        public  IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserva =  _context
                .Reservas
                .Include(x => x.Cliente)
                .Include(x => x.Funcion).ThenInclude(x => x.Pelicula)
                .FirstOrDefault(m => m.Id == id);

            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Role.Administrador))]
        public  IActionResult DeleteConfirmed(int id)
        {
            var reserva =  _context.Reservas.Find(id);
           
            _context.Reservas.Remove(reserva);
            _context.SaveChanges();
            
            return RedirectToAction(nameof(Index));
        }



        ////---- Métodos privados para validaciones ----////

        private bool ReservaExists(int id)
        {
            return _context.Reservas.Any(x => x.Id == id);

        }

        private void ValidarCantButacas(Reserva reserva, Funcion funcion)
        {
            if (funcion.CantButacasDisponibles < reserva.CantButacas)
            {
                ModelState.AddModelError(nameof(reserva.CantButacas), "No hay suficiente cantidad de butacas disponibles para esta función");
            }
        }

        private bool ValidarEdad(Reserva reserva)
        {
            bool puede;

            var funcion = _context.Funciones
                           .Include(x => x.Pelicula).ThenInclude(x => x.Clasificacion)
                           .Where(x => x.Id == reserva.FuncionId)
                           .FirstOrDefault();

            var cliente = _context.Clientes.Find(int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value));
            var fechaNacimiento = cliente.FechaDeNacimiento;
            var fechaActual = DateTime.Now;
            int edad = fechaActual.Year - cliente.FechaDeNacimiento.Year;

            if (fechaActual.Month < fechaNacimiento.Month || (fechaActual.Month == fechaNacimiento.Month && fechaActual.Day < fechaNacimiento.Day))
            {
                edad--;
            }

            if (edad < funcion.Pelicula.Clasificacion.EdadMinima)
            {
                puede = false;
            }
            else
            {
                puede = true;
            }

            return puede;

        }

    }
}

ORT/Grupo3.ReservaDeCine/Views/Funciones/Create.cshtml
@model Grupo3.ReservaDeCine.Models.Funcion

@{
    ViewData["Title"] = "Crear función";
}

<h1>Funciones</h1>
<h4>Crear nueva función</h4>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SalaId" class="control-label"></label>
                <select asp-for="SalaId" class="form-control" asp-items="ViewBag.SelectSalas" required></select>
                <span asp-validation-for="SalaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PeliculaId" class="control-label"></label>
                <select asp-for="PeliculaId" class="form-control" asp-items="ViewBag.SelectPeliculas" required></select>
                <span asp-validation-for="PeliculaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" type="date" class="form-control" required/>
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Horario" class="control-label"></label>
                <input asp-for="Horario" type="time" class="form-control" required/>
                <span asp-validation-for="Horario" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ORT/Grupo3.ReservaDeCine/Views/Funciones/Delete.cshtml
@model Grupo3.ReservaDeCine.Models.Funcion

@{
    ViewData["Title"] = "Eliminar función";
}

<h1>Funciones</h1>
<h3>¿Está seguro que desea eliminar esta función?</h3>

<div> 
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sala)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sala.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pelicula)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pelicula.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class="col-sm-10">
            @Model.Fecha.ToString("dd/MM/yyyy")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Horario)
        </dt>
        <dd class="col-sm-10">
            @Model.Horario.ToString("HH:mm")
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver a la lista</a>
    </form>
</div>

ORT/Grupo3.ReservaDeCine/Views/Funciones/FiltrarPorFecha.cshtml
@model IEnumerable<Grupo3.ReservaDeCine.Models.Funcion>

@{
    ViewData["Title"] = "Próximas funciones";
}

<h3>Próximas funciones</h3>

<table class="table">
    <thead>
        <tr>
            <th>
                Tipo de sala
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pelicula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaHora)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantButacasDisponibles)
            </th>
            <th>
                Precio
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Sala.Tipo.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pelicula.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaHora)
                </td>

                @if (item.CantButacasDisponibles != 0)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.CantButacasDisponibles)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sala.Tipo.PrecioEntrada)
                    </td>
                    <td>
                        <a class="btn btn-outline-secondary custom-select-sm" asp-controller="Reservas" asp-action="CrearReservaPorFuncion" asp-route-id="@item.Id">Reservar</a>
                    </td>
                }
                else
                {
                    <td>
                        <p style="font-weight:bolder; color:red">Agotadas</p>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sala.Tipo.PrecioEntrada)
                    </td>
                    <td>
                        <a class="btn btn-outline-secondary custom-select-sm disabled" disabled asp-controller="Reservas" asp-action="CrearReservaPorFuncion" asp-route-id="@item.Id">Reservar</a>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

ORT/Grupo3.ReservaDeCine/Views/Funciones/FiltrarPorPelicula.cshtml
@model IEnumerable<Grupo3.ReservaDeCine.Models.Funcion>

@{
    ViewData["Title"] = "Próximas funciones";
}

<h3>Próximas funciones</h3>

<table class="table">
    <thead>
        <tr>
            <th>
                Tipo de sala
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PeliculaId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaHora)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantButacasDisponibles)
            </th>
            <th>
                Precio
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Sala.Tipo.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pelicula.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaHora)
                </td>

                @if (item.CantButacasDisponibles != 0)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.CantButacasDisponibles)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sala.Tipo.PrecioEntrada)
                    </td>
                    <td>
                        <a class="btn btn-outline-secondary custom-select-sm" asp-controller="Reservas" asp-action="CrearReservaPorFuncion" asp-route-id="@item.Id">Reservar</a>
                    </td>
                }
                else
                {
                    <td>
                        <p style="font-weight:bolder; color:red">Agotadas</p>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sala.Tipo.PrecioEntrada)
                    </td>
                    <td>
                        <a class="btn btn-outline-secondary custom-select-sm disabled" disabled asp-controller="Reservas" asp-action="CrearReservaPorFuncion" asp-route-id="@item.Id">Reservar</a>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

ORT/Grupo3.ReservaDeCine/Views/Funciones/FiltrarPorPeliculaId.cshtml
@model IEnumerable<Grupo3.ReservaDeCine.Models.Funcion>

@{
    ViewData["Title"] = "Próximas funciones";
}

<h3>Próximas funciones</h3>

<table class="table">
    <thead>
        <tr>
            <th>
                Tipo de sala
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PeliculaId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaHora)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantButacasDisponibles)
            </th>
            <th>
                Precio
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Sala.Tipo.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pelicula.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaHora)
            </td>

            @if (item.CantButacasDisponibles != 0)
            {
                <td>
                    @Html.DisplayFor(modelItem => item.CantButacasDisponibles)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sala.Tipo.PrecioEntrada)
                </td>
                <td>
                    <a class="btn btn-outline-secondary custom-select-sm" asp-controller="Reservas" asp-action="CrearReservaPorFuncion" asp-route-id="@item.Id">Reservar</a>
                </td>
            }
            else
            {
                <td>
                    <p style="font-weight:bolder; color:red">Agotadas</p>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sala.Tipo.PrecioEntrada)
                </td>
                <td>
                    <a class="btn btn-outline-secondary custom-select-sm disabled" disabled asp-controller="Reservas" asp-action="CrearReservaPorFuncion" asp-route-id="@item.Id">Reservar</a>
                </td>
            }
        </tr>
        }
    </tbody>
</table>

ORT/Grupo3.ReservaDeCine/Views/Funciones/NoHayFunciones.cshtml
@{
    ViewData["Title"] = "No Hay Funciones";
}

<h3>No hay ninguna función disponible</h3>
<hr/>
<p>No te pierdas la oportunidad de visitar <i>SuperSmart Cines</i>, <a asp-action="SeleccionarFiltro">intenta otras opciones.</a></p>

ORT/Grupo3.ReservaDeCine/Views/Funciones/SeleccionarFiltro.cshtml
@model Grupo3.ReservaDeCine.Models.Funcion

@{
    ViewData["Title"] = "Seleccionar Filtro";
}

<h3>Seleccionar Filtro</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SeleccionarFiltro">
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" type="text" class="form-control" value="@DateTime.Today.ToString("dd/MM/yyyy")" id="datepicker"  />
            </div>
            <div class="form-group">
                <input type="submit" value="Buscar" class="btn btn-outline-secondary" asp-controller="Funciones" asp-action="FiltrarPorFecha" />
            </div>

            <div class="form-group">
                <label asp-for="PeliculaId" class="control-label"></label>
                <select asp-for="PeliculaId" class="form-control" asp-items="ViewBag.SelectPeliculas" ></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Buscar" class="btn btn-outline-secondary" asp-controller="Funciones" asp-action="FiltrarPorPeliculaId"/>
            </div>

        </form>
    </div>
</div>


<div>
    <a asp-controller="Home" asp-action="Index">Volver al inicio</a>
</div>

@section Scripts {
<script>
    $(function () {
        $('#datepicker').datepicker({
            maxViewMode: 2,
            clearBtn: true,
            language: "es",
            autoclose: true,
            startDate: new Date()
        });
    })
 </script>
}