ORT/Grupo3.ReservaDeCine/Models/Cliente.cs
using Grupo3.ReservaDeCine.Models.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace Grupo3.ReservaDeCine.Models
{
    public class Cliente : Usuario
    {
      
        [Required(ErrorMessage = "El campo Fecha de Nacimiento es requerido")]
        [Display(Name = "Fecha de nacimiento")]
        public DateTime FechaDeNacimiento { get; set; }


        [Display(Name = "Fecha de Alta")]
        public DateTime FechaDeAlta { get; set; }


        [Display(Name = "Reservas")]
        public List<Reserva> Reservas { get; set; }


        [ScaffoldColumn(false)]
        public override Role Role => Role.Cliente;

    }
}

ORT/Grupo3.ReservaDeCine/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Grupo3.ReservaDeCine.Database;
using Grupo3.ReservaDeCine.Models;
using Microsoft.AspNetCore.Authorization;
using Grupo3.ReservaDeCine.Models.Enums;
using System.Security.Claims;
using Grupo3.ReservaDeCine.Extensions;
using System.Text.RegularExpressions;
using ConSeguridad.Controllers;

namespace Grupo3.ReservaDeCine.Controllers
{

    public class ClientesController : Controller
    {
        private readonly CineDbContext _context;

        public ClientesController(CineDbContext context)
        {
            _context = context;
        }


        [HttpGet]
        [Authorize(Roles = nameof(Role.Administrador))]
        public IActionResult Index()
        {
            return View(_context.Clientes.ToList());
        }


        [HttpGet]
        [Authorize]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                id = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            }
            // Esta es la consulta de la base de datos que hacemos a través de Entity Framework.
            // Toda la información que obtengamos de la base será la información que podamos acceder luego desde la variable cliente.
            // Las propiedades de navegación nos servirán para poder "Navegar" desde una propiedad a otra, en este caso desde cliente a sus "Reservas".
            // Para que las propiedades de Navegación sean cargadas es necesario utilizar el Include indicando qué propiedad queremos que se cargue (en este caso Reservas).
            // Luego, si deseamos obtener información específica de algo asociado a la reserva (en nuestro caso la función y dentro de la función la película) debemos hacer include también de eso.
            var cliente =  _context.Clientes
                .Include(x => x.Reservas).ThenInclude(x => x.Funcion).ThenInclude(x => x.Pelicula)
                .FirstOrDefault(x => x.Id == id);
            // Es importante remarcar que la semántica es => Traeme los clientes => con sus reservas => de sus reservas incluíme las funciones => de esas funciones incluíme la película.

            // Luego utilizaremos esta información en la vista.

            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }


        [HttpGet]
        [AllowAnonymous]
        public IActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public IActionResult Registrar([Bind("Nombre, Apellido, FechaDeNacimiento, Email, Username")] Cliente cliente, string password)
        {
            ComprobarFechaDeNacimiento(cliente.FechaDeNacimiento);
            ValidarEmailExistente(cliente.Email, cliente.Id);
            ValidarUserNameExistente(cliente.Username);
            ValidarPassword(password);

            if (ModelState.IsValid)
            {
                cliente.FechaDeAlta = DateTime.Now;
                cliente.Password = password.Encriptar();
                _context.Add(cliente);
                _context.SaveChanges();

                return RedirectToAction(nameof(CreateExitoso));
            }

            return View(cliente);
        }

        public IActionResult CreateExitoso()
        {
            return View();
        }


        [HttpGet]
        [Authorize(Roles = nameof(Role.Administrador))]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente =  _context.Clientes.Find(id);

            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Role.Administrador))]
        public IActionResult Edit(int id, Cliente cliente, string password)
        {
            return EditarCliente(id, cliente, password);
        }

        [HttpGet]
        [Authorize(Roles = nameof(Role.Cliente))]
        public IActionResult EditMe()
        {
            int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out int id);
            var cliente = _context.Clientes.Find(id);

            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Role.Cliente))]
        public IActionResult EditMe([Bind("Id, Nombre, Apellido, FechaDeNacimiento, Email")] Cliente cliente, string password)
        {
            int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out int id);
            
            return EditarCliente(id, cliente, password);
        }


        private IActionResult EditarCliente(int id, Cliente cliente, string password)
        {
            if (cliente.Id != id)
            {
                return NotFound();
            }

            ComprobarFechaDeNacimiento(cliente.FechaDeNacimiento);
            ModelState.Remove(nameof(Cliente.Username));

            if (!string.IsNullOrWhiteSpace(password))
            {
                ValidarPassword(password);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Cliente clienteDb = _context.Clientes.Find(cliente.Id);

                    clienteDb.Email = cliente.Email;
                    clienteDb.FechaDeNacimiento = cliente.FechaDeNacimiento;
                    clienteDb.Nombre = cliente.Nombre;
                    clienteDb.Apellido = cliente.Apellido;

                    if (!string.IsNullOrWhiteSpace(password))
                    {
                        clienteDb.Password = password.Encriptar();
                    }

                    _context.Update(clienteDb);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                if (User.IsInRole(nameof(Role.Administrador)))
                {
                    return RedirectToAction(nameof(Index));
                }

                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            return View(cliente);
        }


        [HttpGet]
        [Authorize(Roles = nameof(Role.Administrador))]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = _context.Clientes
                .FirstOrDefault(x => x.Id == id);

            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Role.Administrador))]
        public IActionResult DeleteConfirmed(int id)
        {
            var cliente =  _context.Clientes.Find(id);
           
            _context.Clientes.Remove(cliente);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }



        ////---- Métodos privados para validaciones ----////

        private bool ClienteExists(int id)
        {
            return _context.Clientes.Any(x => x.Id == id);
        }


        //Edad mínima para crear un usuario: 12 años, Máxima: 100 años.
        private void ComprobarFechaDeNacimiento(DateTime fechaNacimiento)
        {
            var fechaActual = DateTime.Now;
            int edad = fechaActual.Year - fechaNacimiento.Year;

            if (fechaActual.Month < fechaNacimiento.Month || (fechaActual.Month == fechaNacimiento.Month && fechaActual.Day < fechaNacimiento.Day))
            {
                edad--;
            }

            if (edad < 12)
            {
                ModelState.AddModelError(nameof(Cliente.FechaDeNacimiento), "El cliente debe ser mayor de 12 años");
            }

            if (fechaNacimiento.Year < (DateTime.Today.Year - 100) || fechaNacimiento.Year > DateTime.Today.Year)
            {
                ModelState.AddModelError(nameof(Cliente.FechaDeNacimiento), "Fecha de nacimiento inválida");
            }
        }


        private void ValidarUserNameExistente(string username)
        {
            if (_context.Usuarios.Any(x => Comparar(x.Username, username)))
            {
                ModelState.AddModelError(nameof(Cliente.Username), "Nombre de usuario no disponible");
            }
        }


        private void ValidarEmailExistente(string mail, int id)
        {
            if (_context.Clientes.Any(x => Comparar(x.Email, mail) && x.Id != id))
            {
                ModelState.AddModelError(nameof(Cliente.Email), "Ya existe un cliente con este Email");
            }
        }


        private static bool Comparar(string s1, string s2)
        {
            return s1.Where(c => !char.IsWhiteSpace(c)).Select(char.ToUpperInvariant)
                .SequenceEqual(s2.Where(c => !char.IsWhiteSpace(c)).Select(char.ToUpperInvariant));
        }


        public void ValidarPassword(string password)
        {
            if (string.IsNullOrWhiteSpace(password))
            {
                ModelState.AddModelError(nameof(Cliente.Password), "La contraseña es requerida");
            }

            if (password.Length < 8)
            {

ORT/Grupo3.ReservaDeCine/Controllers/CuentasController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Grupo3.ReservaDeCine.Controllers;
using Grupo3.ReservaDeCine.Database;
using Grupo3.ReservaDeCine.Extensions;
using Grupo3.ReservaDeCine.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Grupo3.ReservaDeCine.Models.Enums;

namespace ConSeguridad.Controllers
{
    public class CuentasController : Controller
    {
        private readonly CineDbContext _context;

        public CuentasController(CineDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Ingresar(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Ingresar(string username, string password, string returnUrl)
        {
            if (!string.IsNullOrWhiteSpace(username) && !string.IsNullOrWhiteSpace(password))  // Se valida que se envie usuario y contraseña y que no lleguen vacios
            {
                Usuario usuario = _context.Clientes.FirstOrDefault(x => x.Username == username); // se le pide a la base de datos que encuentre al usuario con ese UserName
              
                if (usuario == null)  // aca se confirma que el usuario exista, sino.. da error
                {
                    usuario = _context.Administradores.FirstOrDefault(x => x.Username == username);
                }

                if (usuario != null)
                {
                    var passwordEncriptada = password.Encriptar();  // encripto la password del formulario con el metodo de extension

                    if (usuario.Password.SequenceEqual(passwordEncriptada)) //comparo cada uno de los elementos del array de la pasword del formulario, con la password de la base de datos
                    {
                        //aca se crea la identidad del usuario que esta ingresando:
                        // esto es para tener informacion relativa a la identidad del usuario, en el contexto actual(!)

                        ClaimsIdentity identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                        identity.AddClaim(new Claim(ClaimTypes.Name, username));
                        identity.AddClaim(new Claim(ClaimTypes.Role, usuario.Role.ToString()));//De aca viene el [Authorize..role]
                        identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, usuario.Id.ToString()));
                        ClaimsPrincipal principal = new ClaimsPrincipal(identity);

                        // en este paso se hace el login del usuario al sistema:
                        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                        usuario.FechaUltimoAcceso = DateTime.Now;
                        _context.SaveChanges();

                        if (!string.IsNullOrWhiteSpace(returnUrl))
                        {
                            return Redirect(returnUrl);

                        }

                        TempData["primerLogin"] = true;  // el tempData, vive dos request por lo que lo puedo usar entre metodos del controlador y levantarlo directamente

                        return RedirectToAction(nameof(HomeController.Index), "Home");
                    }
                }
            }
            ViewBag.Error = "Usuario y/o contraseña incorrectos";
            ViewBag.UserName = username;
            ViewBag.ReturnUrl = returnUrl;

            return View();
        }


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Salir()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        
        [HttpGet]
        public IActionResult NoAutorizado()
        {
            return View();
        }

    }
}

ORT/Grupo3.ReservaDeCine/Views/Clientes/CreateExitoso.cshtml
@{
    ViewData["Title"] = "Bienvenido";
}

<h3>¡Usuario creado con éxito!</h3>
<hr/>
<p>Bienvenido a la comunidad de <i>SuperSmart Cines</i>, iniciá sesión <a asp-controller="Cuentas" asp-action="Ingresar">aquí.</a></p>

ORT/Grupo3.ReservaDeCine/Views/Clientes/Delete.cshtml
@model Grupo3.ReservaDeCine.Models.Cliente

@{
    ViewData["Title"] = "Eliminar cliente";
}

<h1>Clientes</h1>
<h4>¿Está seguro que desea eliminar este Cliente?</h4>

<div>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDeNacimiento)
        </dt>
        <dd class="col-sm-10">
            @Model.FechaDeNacimiento.ToString("dd/MM/yyyy")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDeAlta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaDeAlta)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver a la lista</a>
    </form>
</div>

ORT/Grupo3.ReservaDeCine/Views/Clientes/Details.cshtml
@model Grupo3.ReservaDeCine.Models.Cliente

@{
    ViewData["Title"] = "Datos del cliente";
}

<h1>Cliente</h1>

<div>
    <h4>Detalles</h4>
    <hr />
    <dl class="row">
        @if (User.IsInRole(nameof(Role.Administrador)))
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Id)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Id)
            </dd>
        }
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDeNacimiento)
        </dt>
        <dd class="col-sm-10">
            @Model.FechaDeNacimiento.ToString("dd/MM/yyyy")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDeAlta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaDeAlta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaUltimoAcceso)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaUltimoAcceso)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Reservas)
        </dt>
        <dd class="col-sm-10">
            <ul>
            @foreach (Reserva reserva in Model.Reservas)
            {
            <li>Película: @reserva.Funcion.Pelicula.Nombre, Fecha y hora: @reserva.Funcion.FechaHora, Cantidad de butacas: @reserva.CantButacas</li>
            }
            </ul>
        </dd>
    </dl>
</div>

<div>
    @if (User.IsInRole(nameof(Role.Administrador)))
    {
        <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
        <a asp-action="Index"> | Volver a la lista</a>
    }
    else
    {
        <a asp-action="EditMe" asp-route-id="@Model.Id">Editar mi Perfil</a>
    }

</div>

ORT/Grupo3.ReservaDeCine/Views/Clientes/Edit.cshtml
@model Grupo3.ReservaDeCine.Models.Cliente

@{
    ViewData["Title"] = "Editar cliente";
}

<h1>Clientes</h1>
<h4>Editar Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDeNacimiento" class="control-label"></label>
                <input asp-for="FechaDeNacimiento" type="date" class="form-control" />
                <span asp-validation-for="FechaDeNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input name="password" type="password" class="form-control" id="pass" />
                <span class="small">
                    <input type="checkbox" onclick="verContrasenia()" /> Ver contraseña<br />
                </span>
                <span class="text-success small font-weight-bolder">
                    La contraseña debe contener al menos 8 caracteres, un número, una minúscula y una mayúscula.
                </span><br />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script type="text/javascript">

    function verContrasenia() {
        var contrasenia = document.getElementById('pass');

        if (contrasenia.type === "password") {
            contrasenia.type = "text";
        } else {
            contrasenia.type = "password";
        }
    }
</script>
}

ORT/Grupo3.ReservaDeCine/Views/Clientes/EditMe.cshtml
@model Grupo3.ReservaDeCine.Models.Cliente

@{
    ViewData["Title"] = "Editar mi perfil";
}

<h3>Editar mis datos</h3>

<hr />

<div class="row">
    <div class="col-md-3">
        <form asp-action="EditMe" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDeNacimiento" class="control-label"></label>
                <input asp-for="FechaDeNacimiento" type="date" class="form-control" />
                <span asp-validation-for="FechaDeNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input name="password" type="password" class="form-control" id="pass" />
                <span class="small">
                    <input type="checkbox" onclick="verContrasenia()" /> Ver contraseña<br />
                </span>
                <span class="text-success small font-weight-bolder">
                    La contraseña debe contener al menos 8 caracteres, un número, una minúscula y una mayúscula.
                </span><br />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">

        function verContrasenia() {
            var contrasenia = document.getElementById('pass');

            if (contrasenia.type === "password") {
                contrasenia.type = "text";
            } else {
                contrasenia.type = "password";
            }
        }
    </script>

}

ORT/Grupo3.ReservaDeCine/Views/Clientes/Index.cshtml
@model IEnumerable<Grupo3.ReservaDeCine.Models.Cliente>

@{
    ViewData["Title"] = "Clientes";
}

<h1>Clientes</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaDeNacimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaDeAlta)
            </th>
            <th></th>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @item.FechaDeNacimiento.ToString("dd/MM/yyyy")
            </td>
            <td>
                @item.FechaDeAlta.ToString("dd/MM/yyyy")
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

ORT/Grupo3.ReservaDeCine/Views/Clientes/Registrar.cshtml
@model Grupo3.ReservaDeCine.Models.Cliente

@{
    ViewData["Title"] = "Registrar";
}


<h3>Crear nuevo usuario</h3>
<hr />
<div class="row">
    <div class="col-md-4 align-content-center">
        <form asp-action="Registrar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" minlength=2 maxlength=100 class="form-control" required />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" minlength=2 maxlength=100 class="form-control" required />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" type="email" class="form-control" required />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDeNacimiento" class="control-label"></label>
                <input asp-for="FechaDeNacimiento" type="date" class="form-control" required />
                <span asp-validation-for="FechaDeNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" required />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input name="password" type="password" class="form-control" id="pass" required />
                <span class="small">
                    <input type="checkbox" onclick="verContrasenia()" /> Ver contraseña<br />
                </span>
                <span class="text-success small font-weight-bolder">
                    La contraseña debe contener al menos 8 caracteres, un número, una minúscula y una mayúscula.
                </span><br />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Resgistrarme" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>



@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}


    <script type="text/javascript">

        function verContrasenia() {
            var contrasenia = document.getElementById('pass');

            if (contrasenia.type === "password") {
                contrasenia.type = "text";
            } else {
                contrasenia.type = "password";
            }
        }
    </script>
}